repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [ --autofix, --no-sort-keys ]
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: mixed-line-ending
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.6.0
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]
