site_name: Modern Python Package
repo_name: markdouthwaite/modern-python-package
repo_url: https://github.com/markdouthwaite/modern-python-package

nav:
  - Introduction: 'index.md'

theme:
    name: material

copyright: Copyright &copy; Mark Douthwaite
